"""create_saturday_scales_table

Revision ID: 169ec6a35cfc
Revises: bc9b0175f3db
Create Date: 2026-05-29 14:12:18.074118
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169ec6a35cfc'
down_revision: Union[str, None] = 'bc9b0175f3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saturday_scales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_saturday_scale_employee_date')
    )
    op.create_index(op.f('ix_saturday_scales_date'), 'saturday_scales', ['date'], unique=False)
    op.create_index(op.f('ix_saturday_scales_employee_id'), 'saturday_scales', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saturday_scales_employee_id'), table_name='saturday_scales')
    op.drop_index(op.f('ix_saturday_scales_date'), table_name='saturday_scales')
    op.drop_table('saturday_scales')
    # ### end Alembic commands ###
