"""add_absences_medical_leaves_to_employees

Revision ID: 1f2c99f9f1fd
Revises: fcacdc23e964
Create Date: 2026-05-26 16:30:59.416710
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2c99f9f1fd'
down_revision: Union[str, None] = 'fcacdc23e964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with server_default to handle existing rows, then keep NOT NULL constraint
    op.add_column('employees', sa.Column('absences', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('employees', sa.Column('medical_leaves', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'medical_leaves')
    op.drop_column('employees', 'absences')
    # ### end Alembic commands ###
