"""add_available_unit_ids_to_employees

Revision ID: 9379bfaff420
Revises: 1f2c99f9f1fd
Create Date: 2026-05-26 16:36:40.739405
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9379bfaff420'
down_revision: Union[str, None] = '1f2c99f9f1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add JSON column with empty array as server_default to handle existing rows
    op.add_column('employees', sa.Column('available_unit_ids', sa.JSON(), nullable=False, server_default='[]'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'available_unit_ids')
    # ### end Alembic commands ###
