"""add_employee_start_and_termination_dates

Revision ID: 9b5ed274c569
Revises: ef041c4cde38
Create Date: 2026-05-27 12:36:01.547903
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5ed274c569'
down_revision: Union[str, None] = 'ef041c4cde38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('termination_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'termination_date')
    op.drop_column('employees', 'start_date')
    # ### end Alembic commands ###
