"""add_cnpj_and_rescision

Revision ID: bc9b0175f3db
Revises: 9b5ed274c569
Create Date: 2026-05-29 08:04:07.339801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9b0175f3db'
down_revision: Union[str, None] = '9b5ed274c569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('cnpj', sa.String(length=18), nullable=True))
    op.add_column('employees', sa.Column('rescision_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employees', sa.Column('rescision_type', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('rescision_status', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('rescision_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'rescision_notes')
    op.drop_column('employees', 'rescision_status')
    op.drop_column('employees', 'rescision_type')
    op.drop_column('employees', 'rescision_value')
    op.drop_column('employees', 'cnpj')
    # ### end Alembic commands ###
