"""make_employee_unit_id_nullable

Revision ID: c4ad006ab8cf
Revises: 0d20aaa7af40
Create Date: 2026-05-27 10:36:16.911137
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ad006ab8cf'
down_revision: Union[str, None] = '0d20aaa7af40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'unit_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'unit_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
