"""alter_production_to_unit

Revision ID: fcacdc23e964
Revises: 17109e7c607e
Create Date: 2026-05-26 13:55:10.485913
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcacdc23e964'
down_revision: Union[str, None] = '17109e7c607e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE monthly_production CASCADE;")
    op.add_column('monthly_production', sa.Column('unit_id', sa.UUID(), nullable=False))
    op.drop_index('ix_monthly_production_employee_id', table_name='monthly_production')
    op.drop_constraint('uq_prod_employee_month', 'monthly_production', type_='unique')
    op.create_index(op.f('ix_monthly_production_unit_id'), 'monthly_production', ['unit_id'], unique=False)
    op.create_unique_constraint('uq_prod_unit_month', 'monthly_production', ['unit_id', 'year', 'month'])
    op.drop_constraint('monthly_production_employee_id_fkey', 'monthly_production', type_='foreignkey')
    op.create_foreign_key(None, 'monthly_production', 'units', ['unit_id'], ['id'])
    op.drop_column('monthly_production', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthly_production', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'monthly_production', type_='foreignkey')
    op.create_foreign_key('monthly_production_employee_id_fkey', 'monthly_production', 'employees', ['employee_id'], ['id'])
    op.drop_constraint('uq_prod_unit_month', 'monthly_production', type_='unique')
    op.drop_index(op.f('ix_monthly_production_unit_id'), table_name='monthly_production')
    op.create_unique_constraint('uq_prod_employee_month', 'monthly_production', ['employee_id', 'year', 'month'])
    op.create_index('ix_monthly_production_employee_id', 'monthly_production', ['employee_id'], unique=False)
    op.drop_column('monthly_production', 'unit_id')
    # ### end Alembic commands ###
